---
- include: vireo_user.yml
  tags: ['user']
  become: true

- include: install.yml
  tags: ['install']

- include: configure_db.yml
  tags: ['config, db']

- include: configure_vireo.yml
  tags: ['config, vireo']

- include: vireo_service.yml
  tags: ['service']

- include: branding.yml
  tags: ['branding']
